version: '3.0'

services:
  zomato-reviews-visualize:
    container_name: zomato-reviews-visualize
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3007:3007"
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - NODE_ENV=development

networks:
  default: 
    external:
      name: mongonet